In [12]:
import numpy as np
import pandas as pd

#Defining path to file
path = "/mnt/c/Users/josem/OneDrive/Documents/Dummy_data/new_dummy_data.csv" # r'/path' for windows

# using pandas pd.read_csv(path) I will load in the data
df = pd.read_csv(path)
# Choose three wells to be hot.
hot_wells = [10, 1, 5]

# Start every well at a low background concentration.
df["PCB"] = 5.0

# Give the three selected wells high concentrations.
df.loc[hot_wells, "PCB"] = [1200.0, 1050.0, 850.0]

df

   Well_ID        long        lat     PCB
0    MW-01 -105.613397  36.565473     5.0
1    MW-02 -105.613036  36.565051  1050.0
2    MW-03 -105.613138  36.565514     5.0
3    MW-04 -105.612863  36.564706     5.0
4    MW-05 -105.613287  36.565370     5.0
5    MW-06 -105.613929  36.565913   850.0
6    MW-07 -105.614350  36.565300     5.0
7    MW-08 -105.613328  36.564878     5.0
8    MW-09 -105.614225  36.565876     5.0
9    MW-10 -105.613779  36.565348     5.0
10   MW-11 -105.613602  36.565087  1200.0
11   MW-12 -105.612720  36.565258     5.0
12   MW-13 -105.613666  36.565928     5.0
13   MW-14 -105.613088  36.565981     5.0
14   MW-15 -105.614094  36.565019     5.0

In [13]:
rng = np.random.default_rng(42)

cold_wells = ~df.index.isin(hot_wells)
df.loc[cold_wells, "PCB"] = rng.uniform(
    low=0.01,
    high=10.0,
    size=cold_wells.sum(),
)

df

   Well_ID        long        lat          PCB
0    MW-01 -105.613397  36.565473     7.741821
1    MW-02 -105.613036  36.565051  1050.000000
2    MW-03 -105.613138  36.565514     4.394396
3    MW-04 -105.612863  36.564706     8.587393
4    MW-05 -105.613287  36.565370     6.976707
5    MW-06 -105.613929  36.565913   850.000000
6    MW-07 -105.614350  36.565300     0.950832
7    MW-08 -105.613328  36.564878     9.756467
8    MW-09 -105.614225  36.565876     7.613786
9    MW-10 -105.613779  36.565348     7.862782
10   MW-11 -105.613602  36.565087  1200.000000
11   MW-12 -105.612720  36.565258     1.289855
12   MW-13 -105.613666  36.565928     4.509356
13   MW-14 -105.613088  36.565981     3.714272
14   MW-15 -105.614094  36.565019     9.268382

In [14]:
df["PCB"] = df["PCB"].astype(int)
df

   Well_ID        long        lat   PCB
0    MW-01 -105.613397  36.565473     7
1    MW-02 -105.613036  36.565051  1050
2    MW-03 -105.613138  36.565514     4
3    MW-04 -105.612863  36.564706     8
4    MW-05 -105.613287  36.565370     6
5    MW-06 -105.613929  36.565913   850
6    MW-07 -105.614350  36.565300     0
7    MW-08 -105.613328  36.564878     9
8    MW-09 -105.614225  36.565876     7
9    MW-10 -105.613779  36.565348     7
10   MW-11 -105.613602  36.565087  1200
11   MW-12 -105.612720  36.565258     1
12   MW-13 -105.613666  36.565928     4
13   MW-14 -105.613088  36.565981     3
14   MW-15 -105.614094  36.565019     9

In [16]:
df.to_csv('/mnt/c/Users/josem/OneDrive/Documents/Dummy_data/new_dummy_data2.csv', index=False)